version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  apt_packages:
    - tree
  jobs:
    post_install:
     - tree /home/docs/checkouts/readthedocs.org/user_builds/mailinglogger/
python:
  install:
    - method: pip
      path: .
      extra_requirements:
         - build
sphinx:
  fail_on_warning: true
